### ISSUE TITLE
Add utility classes

### ISSUE THREAD

**Issue by scanieso** [freshtilledsoil/base-style-framework#2]
We should include helper classes, such as

``` css
.is-hidden {}
.is-removed {}
```

**Comment by scottaohara** [comment]
Agreed.

I usually do:
.is-visually-hidden  or  .is-a11y-hidden {
  color: transparent;
  position: absolute;
  left: -99999px;
}

.is-temp-hidden {
  opacity: 0;
  visibility: hidden;

  // optional properties
  height: 1px;
  position: absolute;
  transition: opacity .2s;
}

.d-none {
  display: none;
}

I imagine your .is-hidden would map to my first set of classes and is-removed would be display none?

I like having a temp hidden, because I've found it useful for things like modals, that need to be hidden but then usually have a transition to bring them into view.  Hence the opacity 0 and visibility hidden, so on state change, the opacity can transition in from zero, as opposed to just blinking into view, which would happen if it was just set to display none by default.

**Comment by scanieso** [comment]
Yup, that's what I was thinking.

Perhaps we can have mixins or silent class names to be used how lead dev sees fit?

I typically house these types of classes inside a `_helpers.scss` asset in `base`, but open to suggestions where they should live.

**Comment by scottaohara** [comment]
maybe a path we take is creating helper classes as only silent classes, so that it's a deliberate effort to include the helper class, as a class name the dev is familiar working with, but make available various helpers that could be useful for a project?
